# Site settings
title: Freelancer
email: siddharthghedia@domain.com
url: https://siddharthghedia.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Web Developer - User Experience Designer"
meta_author: Ghedia Siddharth

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: sid

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Siddharth Ghedia
  location: India
  social: www.facebook.com/sidghedia
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/siddharthghedia
  - title: facebook
    url: https://www.facebook.com/sidghedia
  - title: stack-overflow
    url: http://stackexchange.com/users/4822220/siddharth
  - title: bitbucket
    url: https://bitbucket.org/siddharthghedia
  - title: github
    url: https://github.com/siddharthghedia

# Postal address (add as many lines as necessary)
address:
  - line: Rajkot, Gujarat, India
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'testing'

# Build settings
markdown: kramdown
permalink: pretty
